version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - python --version
      - yum install -y jq
  pre_build:
    commands:
      - >-
        ls -las
      - chmod +x *.sh
      - ./update-taskcat.sh $PIPELINE_BUCKET
  build:
    commands:
      - echo In buildspec-setup.yml Build started on `date`
      -
      - >-
        zip -r ceoa-examples.zip . -x '*.git*'
      - >-
        zip -r ceoa-3-examples.zip ./lesson3-develop -j -x '*.git*'
      - >-
        aws s3 sync . s3://$PIPELINE_BUCKET
  post_build:
    commands:
      - echo In buildspec-setup.yml Build completed on `date`
artifacts:
  files:
    - '**/*'
