---
AWSTemplateFormatVersion: '2010-09-09'
Description: Create an SQS Queue
Resources:
  MyQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${SQSQueueName}
Outputs:
  SourceQueueARN: 
    Description: "ARN of source queue"
    Value: 
      Fn::GetAtt: 
        - "MyQueue"
        - "Arn"